spring:
  datasource:
    url: jdbc:mysql://localhost:3306/senapplimed_hdj
    username: admin
    password: passer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true